<a href="https://colab.research.google.com/github/IMI1998/Persian-text-mining/blob/main/Persian_text_mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/content/per.csv' , encoding='utf-8')

In [3]:
data.head(5)

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

In [4]:
with open('/content/stopwords.txt' , encoding='utf8') as stopwords_file:
  stopwords = stopwords_file.readlines()
  stopwords= [line.replace('\n' , '') for line in stopwords]
  print(stopwords)

['!', '"', '#', '(', ')', '*', ',', '-', '.', '/', ':', '[', ']', '«', '»', '،', '؛', '؟', 'آباد', 'آخ', 'آخر', 'آخرها', 'آخه', 'آدمهاست', 'آرام', 'آرام آرام', 'آره', 'آری', 'آزادانه', 'آسان', 'آسیب پذیرند', 'آشنایند', 'آشکارا', 'آقا', 'آقای', 'آقایان', 'آمد', 'آمدن', 'آمده', 'آمرانه', 'آن', 'آن گاه', 'آنان', 'آنانی', 'آنجا', 'آنرا', 'آنطور', 'آنقدر', 'آنها', 'آنهاست', 'آنچنان', 'آنچنان که', 'آنچه', 'آنکه', 'آنگاه', 'آن\u200cها', 'آهان', 'آهای', 'آور', 'آورد', 'آوردن', 'آورده', 'آوه', 'آی', 'آیا', 'آید', 'آیند', 'ا', 'اتفاقا', 'اثرِ', 'اجراست', 'احتراما', 'احتمالا', 'احیاناً', 'اخیر', 'اخیراً', 'اری', 'از', 'از آن پس', 'از جمله', 'ازاین رو', 'ازجمله', 'ازش', 'اساسا', 'اساساً', 'است', 'استفاد', 'استفاده', 'اسلامی اند', 'اش', 'اشتباها', 'اشکارا', 'اصلا', 'اصلاً', 'اصولا', 'اصولاً', 'اعلام', 'اغلب', 'افزود', 'افسوس', 'اقل', 'اقلیت', 'الا', 'الان', 'البته', 'البتّه', 'الهی', 'الی', 'ام', 'اما', 'امروز', 'امروزه', 'امسال', 'امشب', 'امور', 'امیدوارم', 'امیدوارند', 'امیدواریم', 'ان', 'ان شاأا

In [5]:
import nltk

In [6]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
nltk_downloads = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_downloads)
len(stopwords)

1495

In [8]:
import hazm
stemmer = hazm.Stemmer()
stemmer.stem('کتاب ها')

'کتاب '

In [9]:
from hazm import word_tokenize

In [10]:
dataset = pd.DataFrame(columns=('title_body' , 'category'))
for index , row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenizer = word_tokenize(title_body)
    title_body_tokenizer_filtred = [word for word in title_body_tokenizer if word not in stopwords]
    title_body_tokenizer_filtred_stemmed = [stemmer.stem(word) for word in title_body_tokenizer_filtred]

    dataset.loc[index] = {
        'title_body': ' '.join( title_body_tokenizer_filtred_stemmed),
        'category': row['Category2'].replace('\n', '')
    }

In [11]:
dataset.head(5)

title_body category
0  وزير علو درجمع استاد نمونه سن بازنشستگي استاد ...   آموزشي
1  گردهمايي دانش‌آموختگ موسسه آموز عالي سوره برگز...   آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...   آموزشي
3  هماي يكروزه آسيب شناسي مفهو روابط عمومي بابلسر...  اجتماعي
4  وضعي اقتصادي ميز تحصيل والدين مهمترين عوامل مو...   آموزشي

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
vectorizer = TfidfVectorizer ()

In [14]:
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [15]:
import pickle
with open ('vectorizer.jsdh' , 'wb') as f:
      pickle.dump(vectorizer , f)

In [16]:
X = vectorizer.transform(dataset['title_body'])

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [19]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [20]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']


In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train , x_test , y_train , y_test = train_test_split(X,y)

In [25]:
from sklearn import svm

In [26]:
svmc= svm.SVC()
svmc.fit(x_train , y_train)

SVC()

In [27]:
svmc.score(x_test ,y_test )

0.8374545454545455

In [28]:
from sklearn.metrics import classification_report , confusion_matrix
y_pred=svmc.predict(x_test)

In [29]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       245
           1       0.59      0.63      0.61       243
           2       0.81      0.81      0.81       256
           3       0.83      0.98      0.90       259
           4       0.91      0.91      0.91       252
           5       0.80      0.71      0.75       254
           6       0.82      0.69      0.75       251
           7       0.83      0.85      0.84       257
           8       0.88      0.88      0.88       238
           9       0.95      0.92      0.93       246
          10       0.98      0.95      0.96       249

    accuracy                           0.84      2750
   macro avg       0.84      0.84      0.84      2750
weighted avg       0.84      0.84      0.84      2750



In [30]:
print(confusion_matrix(y_test , y_pred))

[[216  11   0   4   0   3   9   2   0   0   0]
 [ 11 153  22  11   2  13   8  12   6   3   2]
 [  0  23 208   4   0   7   9   4   1   0   0]
 [  0   3   0 253   0   0   3   0   0   0   0]
 [  3   5   2   0 230   7   0   1   3   1   0]
 [  2  17  12   3  11 180   5   9  13   1   1]
 [ 22   8   8  25   1   3 172   9   0   1   2]
 [  3  14   0   1   7   3   3 219   3   4   0]
 [  0   6   3   2   3   7   1   4 209   2   1]
 [  0  13   2   0   0   1   0   3   1 226   0]
 [  0   5   1   1   0   2   0   2   1   0 237]]
